name: Trigger Deploy in Quartz Repository

on:
  push:
    branches: ["main"]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: DRaichev/Erasmus-YE-Green-is-the-new-black-quartz
          event-type: trigger-deploy
          client-payload: '{"ref": "main", "sha": "${{ github.sha }}"}'
