name: Trigger Deploy from External Repository

on:
  repository_dispatch:
    types: [trigger-deploy]

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Deploy Workflow
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: trigger-deploy
          client-payload: '{"ref": "main", "sha": "${{ github.sha }}"}' 
